export const ALGORITHMS_HAS_ERRORED = 'ALGORITHMS_HAS_ERRORED';
export const ALGORITHMS_IS_LOADING = 'ALGORITHMS_IS_LOADING';
export const ALGORITHMS_FETCH_DATA_SUCCESS = 'ALGORITHMS_FETCH_DATA_SUCCESS';

export const BACKTESTS_HAS_ERRORED = 'BACKTESTS_HAS_ERRORED';
export const BACKTESTS_IS_LOADING = 'BACKTESTS_IS_LOADING';
export const BACKTESTS_FETCH_DATA_SUCCESS = 'BACKTESTS_FETCH_DATA_SUCCESS';

export const DAYS_HAS_ERRORED = 'DAYS_HAS_ERRORED';
export const DAYS_IS_LOADING = 'DAYS_IS_LOADING';
export const DAYS_FETCH_DATA_SUCCESS = 'DAYS_FETCH_DATA_SUCCESS';

export const DAILY_RESULT_HAS_ERRORED = 'DAILY_RESULT_HAS_ERRORED';
export const DAILY_RESULT_IS_LOADING = 'DAILY_RESULT_IS_LOADING';
export const DAILY_RESULT_FETCH_DATA_SUCCESS = 'DAILY_RESULT_FETCH_DATA_SUCCESS';
