export const ALGORITHMS_HAS_ERRORED = 'ALGORITHMS_HAS_ERRORED';
export const ALGORITHMS_IS_LOADING = 'ALGORITHMS_IS_LOADING';
export const ALGORITHMS_FETCH_DATA_SUCCESS = 'ALGORITHMS_FETCH_DATA_SUCCESS';

export const TEMPLATES_HAS_ERRORED = 'TEMPLATES_HAS_ERRORED';
export const TEMPLATES_IS_LOADING = 'TEMPLATES_IS_LOADING';
export const TEMPLATES_FETCH_DATA_SUCCESS = 'TEMPLATES_FETCH_DATA_SUCCESS';

export const BACKTESTS_HAS_ERRORED = 'BACKTESTS_HAS_ERRORED';
export const BACKTESTS_IS_LOADING = 'BACKTESTS_IS_LOADING';
export const BACKTESTS_FETCH_DATA_SUCCESS = 'BACKTESTS_FETCH_DATA_SUCCESS';

export const SIMULATION_HAS_ERRORED = 'SIMULATION_HAS_ERRORED';
export const SIMULATION_IS_LOADING = 'SIMULATION_IS_LOADING';
export const SIMULATION_FETCH_DATA_SUCCESS = 'SIMULATION_FETCH_DATA_SUCCESS';

export const DAILY_RESULT_HAS_ERRORED = 'DAILY_RESULT_HAS_ERRORED';
export const DAILY_RESULT_IS_LOADING = 'DAILY_RESULT_IS_LOADING';
export const QUOTES_FETCH_DATA_SUCCESS = 'QUOTES_FETCH_DATA_SUCCESS';
export const TRADES_FETCH_DATA_SUCCESS = 'TRADES_FETCH_DATA_SUCCESS';

export const SIMULATIONS_HAS_ERRORED = 'SIMULATIONS_HAS_ERRORED';
export const SIMULATIONS_IS_LOADING = 'SIMULATIONS_IS_LOADING';
export const SIMULATIONS_FETCH_DATA_SUCCESS = 'SIMULATIONS_FETCH_DATA_SUCCESS';

export const TICKERS_HAS_ERRORED = 'TICKERS_HAS_ERRORED';
export const TICKERS_IS_LOADING = 'TICKERS_IS_LOADING';
export const TICKERS_FETCH_DATA_SUCCESS = 'TICKERS_FETCH_DATA_SUCCESS';